import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import Web3 from 'web3'
import { contractAbi, contractAddress } from '../config'

const web3 = new Web3(Web3.givenProvider)

export default function Home() {
  const [member, setMember] = useState({})
  const [name, setName] = useState()
  const [referral, setReferral] = useState()

  const workshopContract = new web3.eth.Contract(contractAbi, contractAddress)

  const handleConnect = () => {
    Web3.givenProvider.request({ method: 'eth_requestAccounts' })
  }

  useEffect(() => {
    handleConnect()
    handleGetMember()
  }, [])

  const handleGetMember = async () => {
    console.log(Web3.givenProvider?.selectedAddress)
    const _member = await workshopContract.methods.members(Web3.givenProvider?.selectedAddress).call()
    setMember(_member)
  }

  const handleRegistration = () => {
    workshopContract.methods.registration(name, referral || '0x0000000000000000000000000000000000000000')
      .send({ from: Web3.givenProvider?.selectedAddress, value: 10 ** 9 })
      .on('receipt', () => {
        alert('Sukses')
      })
      .on('error', () => {
        alert('Error')
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>connected address: {Web3.givenProvider?.selectedAddress || '-'}</div>
        <h1 className={styles.title}>
          Workshop web3 blockchain, only 1 gwei!
        </h1>

        <p className={styles.description}>
          {member.isMember ? `${member.name} already registered!` : ''}
        </p>

        <div>
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }} type="text" placeholder="name" value={name} onChange={(e) => setName(e.target.value)} />
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }}  type="text" placeholder="referral (optional)" value={referral} onChange={(e) => setReferral(e.target.value)} />
          <button style={{ height: '3rem' }} onClick={handleRegistration}>Register!</button>
        </div>
      </main>
    </div>
  )
}
