import Head from 'next/head'
import { useState, useEffect } from 'react'
import styles from '../../styles/Home.module.css'
import { useEthers, useContractFunction, useCall } from '@usedapp/core'
import { Contract, utils } from 'ethers'
import Web3 from 'web3'
import { contractAbi, contractAddress } from '../config'

export default function Home() {
  const { activateBrowserWallet, account } = useEthers()
  const [name, setName] = useState()
  const [referral, setReferral] = useState()

  const contractWorkshop = new Contract(contractAddress, new utils.Interface(contractAbi))

  const { send: sendRegistration } = useContractFunction(contractWorkshop, 'registration')
  const { value: member } = useCall({
    contract: contractWorkshop,
    method: 'members',
    args: [account]
  }) ?? {}

  const handleConnect = () => activateBrowserWallet()

  useEffect(() => {
    handleConnect()
  }, [])

  const handleRegistration = () => {
    sendRegistration(name, referral || '0x0000000000000000000000000000000000000000', { value: 10 ** 9 })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>connected address: {Web3.givenProvider?.selectedAddress || '-'}</div>
        <h1 className={styles.title}>
          Workshop web3 blockchain, only 1 gwei!
        </h1>

        <p className={styles.description}>
          {member?.['isMember'] ? `${member?.['name']} already registered!` : ''}
        </p>

        <div>
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }} type="text" placeholder="name" value={name} onChange={(e) => setName(e.target.value)} />
          <input style={{
            height: '3rem',
            padding: '2px 4px',
            marginRight: '8px'
          }}  type="text" placeholder="referral (optional)" value={referral} onChange={(e) => setReferral(e.target.value)} />
          <button style={{ height: '3rem' }} onClick={handleRegistration}>Register!</button>
        </div>
      </main>
    </div>
  )
}
